examples: inspect Cabal file from index instead of from working copy
Non-indexed parts of a Cabal file may refer to files not included
in commit.  Inspecting these parts could result in false-positives.

diff --git a/examples/pre-commit b/examples/pre-commit
--- a/examples/pre-commit
+++ b/examples/pre-commit
@@ -13,13 +13,17 @@ for cabal in `find -name '*.cabal'`; do
     if ! is_tracked "$cabal"; then
         continue
     fi
-    sources="`cabal-list-sources "$cabal"`"
+
+    dir="`dirname $cabal`"
+    pushd "$dir" >/dev/null
+    sources="$(git cat-file blob :"`basename "$cabal"`" | cabal-list-sources)"
     for file in $sources; do
         if ! is_tracked "$file"; then
-            echo >&2 "`basename "$0"`: error: forgot to git add $file"
+            echo >&2 "`basename "$0"`: error: forgot to git add $dir/$file"
             exit_code=1
         fi
     done
+    popd >/dev/null
 done
 
 exit $exit_code
